import streamlit as st


stock_symbol = st.sidebar.selectbox("Select Stock", [
    "RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", 
    "LT.NS", "AXISBANK.NS", "ITC.NS", "BAJFINANCE.NS", "HINDUNILVR.NS", "BHARTIARTL.NS", 
    "MARUTI.NS", "SUNPHARMA.NS", "WIPRO.NS", "NTPC.NS", "M&M.NS", "ULTRACEMCO.NS", 
    "ADANIGREEN.NS", "GRASIM.NS", "RELIANCEPOWER.NS", "EICHERMOT.NS", "HCLTECH.NS", 
    "ADANIPORTS.NS", "TATAMOTORS.NS", "POWERGRID.NS", "TATACONSUM.NS", "KOTAKBANK.NS", 
    "INDUSINDBK.NS", "SHREECEM.NS", "ASIANPAINT.NS", "SBILIFE.NS", "MARICO.NS", "BHEL.NS", 
    "HDFCLIFE.NS", "BANKBARODA.NS", "RELIANCEINFRA.NS", "TATACHEM.NS", "DIVISLAB.NS", 
    "COALINDIA.NS", "CIPLA.NS", "MOTHERSONSUMI.NS", "GAIL.NS", "HINDALCO.NS", 
    "TATASTEEL.NS", "JSWSTEEL.NS", "TATAPOWER.NS", "INDIACEM.NS", "RBLBANK.NS", 
    "HINDPETRO.NS", "DABUR.NS", "DRREDDY.NS", "CUB.NS", "PFC.NS", "TATAMETALI.NS", 
    "NBCC.NS", "IOCL.NS", "NESTLEIND.NS", "VEDL.NS", "HEROMOTOCO.NS", "HDFCAMC.NS", 
    "BAJAJ-AUTO.NS", "HINDZINC.NS", "INDIAMART.NS", "BOSCHLTD.NS", "MUTHOOTFIN.NS", 
    "CUMMINSIND.NS", "TATAGLOBAL.NS", "TATAMTRDVR.NS", "AUROPHARMA.NS", "IPCALAB.NS", 
    "PGHH.NS", "BIOCON.NS", "STAR.NS", "BIRLACORPN.NS", "JUBLFOOD.NS", "BERGEPAINT.NS", 
    "ALOKINDS.NS", "TATACOFFEE.NS", "SBI.NS", "BEL.NS", "MANAPPURAM.NS", "DEEPAKNTR.NS", 
    "JKTYRE.NS", "SPICEJET.NS", "BALKRISHNA.NS", "M&MFIN.NS", "DCMSHRIRAM.NS", 
    "GRANULES.NS", "IRCTC.NS", "MAXHEALTH.NS", "PIIND.NS", "GICRE.NS", "NOCIL.NS", 
    "HINDCOPPER.NS", "PIRAMILENTERPRISES.NS", "JKCEMENT.NS", "SAIL.NS", "INDHOTEL.NS", 
    "RELIANCESEC.NS", "TITAN.NS", "BHARATFORGE.NS", "NLCINDIA.NS", "TORNTPHARM.NS", 
    "BATAINDIA.NS", "EXIDEIND.NS", "VSTTILLERS.NS", "DELTACORP.NS", "GUJFLUORO.NS", 
    "NATCOPHARM.NS", "SYNGENE.NS", "CHOLAFIN.NS", "LUPIN.NS", "GMRINFRA.NS", 
    "CGPOWER.NS", "FSL.NS", "RELIANCEDEFENCE.NS", "CESC.NS", "INFIBEAM.NS", 
    "AUFINSERV.NS", "MOTHERSUMI.NS", "IRBINFRA.NS", "KECINTERNATIONAL.NS", 
    "SUNDARAMF.IN", "IFCI.NS", "RUSHIL.NS", "STERLINBIO.NS", "ESCORTS.NS", 
    "DIXONTECH.NS", "PETRONET.NS", "JINDALSTEL.NS", "M&MFIN.NS", "SAIL.NS", 
    "RAJESHEXPO.NS", "GODREJCP.NS", "GUJALKALI.NS", "NHPC.NS", "JAMNAAUTO.NS"
])

# utils/stock_list.py
import streamlit as st

def get_stock_list():
    # This should return a dictionary, not a set
    return {
        "Reliance": "RELIANCE.NS",
        "TCS": "TCS.NS",
        "Infosys": "INFY.NS",
        "HDFC": "HDFC.NS",
        # Add more stocks...
    }
